REM Generate, sort, and analyze 100000 random integers
RANDOMIZE TIMER
DIM VALUES(99999)
DIM FREQUENCY(20000)
FOR I = 0 TO 20000
FREQUENCY(I) = 0
NEXT I
COUNT = 100000
START = TIMER
TOTAL = 0
FOR I = 0 TO COUNT - 1
VALUES(I) = INT(RND * 20001) - 10000
TOTAL = TOTAL + VALUES(I)
FREQUENCY(VALUES(I) + 10000) = FREQUENCY(VALUES(I) + 10000) + 1
NEXT I
GAP = INT(COUNT / 2)
WHILE GAP > 0
FOR I = GAP TO COUNT - 1
TEMP = VALUES(I)
J = I
IF J < GAP THEN GOTO 260
IF VALUES(J - GAP) <= TEMP THEN GOTO 260
VALUES(J) = VALUES(J - GAP)
J = J - GAP
GOTO 210
VALUES(J) = TEMP
NEXT I
GAP = INT(GAP / 2)
WEND
MEAN = TOTAL / COUNT
MEDIAN = (VALUES(49999) + VALUES(50000)) / 2
MODE_COUNT = 0
FOR I = 0 TO 20000
IF FREQUENCY(I) > MODE_COUNT THEN MODE_COUNT = FREQUENCY(I)
NEXT I
FINISH = TIMER
PRINT "Random integer statistics"
PRINT "Range: -10000 to 10000; count: "; COUNT
PRINT "Elapsed compute time (seconds): "; FINISH - START
PRINT "Mean: "; MEAN
PRINT "Median: "; MEDIAN
PRINT "Mode(s) with "; MODE_COUNT; " occurrences: ";
FOR I = 0 TO 20000
IF FREQUENCY(I) = MODE_COUNT THEN PRINT I - 10000; " ";
NEXT I
PRINT
END