' _FULLSCREEN [_STRETCH|_SQUAREPIXELS|_OFF][, _SMOOTH] and the _FULLSCREEN
' function (0 off, 1 stretch, 2 square pixels).
DIM PASS AS INTEGER
PASS = 1
OPEN "tests/fullscreen.result" FOR OUTPUT AS #1
SCREEN 12
IF _FULLSCREEN <> 0 THEN PASS = 0: PRINT #1, "start"; _FULLSCREEN
_FULLSCREEN
IF _FULLSCREEN <> 1 THEN PASS = 0: PRINT #1, "default"; _FULLSCREEN
_FULLSCREEN _SQUAREPIXELS, _SMOOTH
IF _FULLSCREEN <> 2 THEN PASS = 0: PRINT #1, "square"; _FULLSCREEN
PSET (10, 10), 14
_FULLSCREEN _STRETCH
IF _FULLSCREEN <> 1 THEN PASS = 0: PRINT #1, "stretch"; _FULLSCREEN
_FULLSCREEN _OFF
IF _FULLSCREEN <> 0 THEN PASS = 0: PRINT #1, "off"; _FULLSCREEN
errors = 0
ON ERROR GOTO bad
_FULLSCREEN _SQUAREPIXELS, _WOBBLY
ON ERROR GOTO 0
IF errors <> 1 THEN PASS = 0: PRINT #1, "errors"; errors
PRINT #1, PASS
CLOSE #1
SYSTEM
bad: errors = errors + 1: RESUME NEXT
