#ifndef COMMON_H
#define COMMON_H

#define BASIKA_VERSION "0.99.3"
#define BASIC_STRING_MAX (64 * 1024) // Legacy temporary-buffer limit; runtime strings grow dynamically.
#define BASIC_TOKEN_TEXT_MAX 256

typedef enum {
    TOKEN_NUMBER, TOKEN_STRING, TOKEN_IDENTIFIER,
    TOKEN_PRINT, TOKEN_REVERSE, TOKEN_GOTO, TOKEN_LIST, TOKEN_RUN, 
    TOKEN_SYSTEM, TOKEN_QUIT, TOKEN_LET, TOKEN_NEW, TOKEN_EQUALS,
    TOKEN_PSET, TOKEN_LINE, TOKEN_CIRCLE, TOKEN_PAINT, TOKEN_SCREEN, TOKEN_LOCATE, TOKEN_COLOR,
    TOKEN_IF, TOKEN_THEN, TOKEN_ELSE, TOKEN_END, TOKEN_REM, TOKEN_GOSUB, TOKEN_RETURN, TOKEN_DIM, TOKEN_DEF,
    TOKEN_FOR, TOKEN_TO, TOKEN_NEXT, TOKEN_STEP, TOKEN_CLS, TOKEN_SLEEP,
    TOKEN_OPEN, TOKEN_CLOSE, TOKEN_AS, TOKEN_NAME, TOKEN_INPUT, TOKEN_SEEK, TOKEN_DELETE, TOKEN_DATA, TOKEN_READ, TOKEN_RESTORE, TOKEN_RANDOMIZE, TOKEN_KILL, TOKEN_FILES, TOKEN_CHDIR, TOKEN_MKDIR, TOKEN_RMDIR, TOKEN_SHELL, TOKEN_ERASE, TOKEN_FIELD, TOKEN_LSET, TOKEN_RSET, TOKEN_LINE_INPUT, TOKEN_EOF_FUNC,
    TOKEN_DRAW, TOKEN_OPTION, TOKEN_BASE, TOKEN_WINDOW, TOKEN_VIEW,
    TOKEN_DEFINT, TOKEN_DEFSTR, TOKEN_DEFSNG, TOKEN_DEFDBL,
    TOKEN_USING, TOKEN_APOSTROPHE,
    TOKEN_PUT, TOKEN_GET, TOKEN_GETS,
    TOKEN_WHILE, TOKEN_WEND, TOKEN_KEY, TOKEN_INKEY, TOKEN_TIMER, TOKEN_STRIG,
    TOKEN_BEEP,
    TOKEN_PLAY, TOKEN_SOUND,
    TOKEN_PEEK, TOKEN_POKE, TOKEN_VARPTR,
    TOKEN_LEFT, TOKEN_RIGHT, TOKEN_MID,
    TOKEN_SPACE, TOKEN_SPC, TOKEN_STRING_FUNC,
    TOKEN_SWAP, TOKEN_ON, TOKEN_OFF, TOKEN_ERR,
    TOKEN_TIME, TOKEN_DATE,
    TOKEN_INSTR, TOKEN_STR, TOKEN_VAL, TOKEN_RESUME, TOKEN_ENVIRON,
    TOKEN_ASC, TOKEN_CHR, TOKEN_TAB, TOKEN_LEN,
    TOKEN_ARGC,
    TOKEN_ARGVS,
    TOKEN_SCREENSHOT, TOKEN_NEWIMAGE, TOKEN_LOADIMAGE, TOKEN_FREEIMAGE, TOKEN_PUTIMAGE, TOKEN_PRINTSTRING, TOKEN_PRINTWIDTH,
    TOKEN_DEFLATE, TOKEN_INFLATE,
    TOKEN_LOADFONT, TOKEN_FONT, TOKEN_FREEFONT,
    TOKEN_COMMANDS,
    TOKEN_AND, TOKEN_OR, TOKEN_XOR, TOKEN_NOT,
    TOKEN_LOF, TOKEN_LOC,
    TOKEN_UCASE, TOKEN_LCASE, TOKEN_TRIM, TOKEN_LTRIM, TOKEN_RTRIM, TOKEN_HEX, TOKEN_OCT,
    TOKEN_MKI, TOKEN_MKS, TOKEN_MKD, TOKEN_CVI, TOKEN_CVS, TOKEN_CVD,
    TOKEN_EOF, TOKEN_ERROR, TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_COLON, TOKEN_LESS, TOKEN_GREATER,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_LPAREN, TOKEN_RPAREN, 
    TOKEN_POWER, TOKEN_MOD, TOKEN_IDIV, TOKEN_HASH,
    TOKEN_ABS, TOKEN_SQR, TOKEN_SIN, TOKEN_COS, TOKEN_TAN, TOKEN_ATN, 
    TOKEN_EXP, TOKEN_LOG, TOKEN_INT, TOKEN_FIX, TOKEN_RND, TOKEN_SGN
} TokenType;

typedef struct {
    TokenType type;
    char text[BASIC_TOKEN_TEXT_MAX];
    int int_val;
    double double_val;
    int is_double;
    const char *start_ptr;
    int var_idx;
    unsigned int type_generation;
} Token;

typedef struct Statement {
    int line_number;
    char label[64];
    char raw_command[256];
    Token *tokens;
    int token_count;
    struct Statement *next;
} Statement;

// Simple variable storage
typedef struct {
    unsigned char *data;
    size_t length;
    size_t capacity;
    int is_fixed; // Flag to enforce fixed size behavior (0 = dynamic, 1 = fixed)
    size_t fixed_length;
} BasicString;

int basic_string_assign(BasicString **target, const void *data, size_t length);
int basic_string_append(BasicString *target, const void *data, size_t length);

typedef struct {
    char name[32];
    double value;
    BasicString *s_value;
    double *array;
    BasicString **s_array;
    int array_size;
    int num_dims;
    int dims[3];  // Support up to 3D arrays
    int string_declared;
    size_t string_fixed_length;
} Variable;

typedef enum {
    ERR_NONE = 0,
    ERR_NEXT_WITHOUT_FOR = 1,
    ERR_SYNTAX_ERROR = 2,
    ERR_RETURN_WITHOUT_GOSUB = 3,
    ERR_OUT_OF_DATA = 4,
    ERR_ILLEGAL_FUNCTION_CALL = 5,
    ERR_OVERFLOW = 6,
    ERR_OUT_OF_MEMORY = 7,
    ERR_UNDEFINED_LINE_NUMBER = 8,
    ERR_SUBSCRIPT_OUT_OF_RANGE = 9,
    ERR_DUPLICATE_DEFINITION = 10,
    ERR_DIVISION_BY_ZERO = 11,
    ERR_TYPE_MISMATCH = 13,
    ERR_OUT_OF_STRING_SPACE = 14,
    ERR_CANT_RESUME = 19,
    ERR_RESUME_WITHOUT_ERROR = 20,
    ERR_FOR_WITHOUT_NEXT = 26,
    ERR_WHILE_WITHOUT_WEND = 29,
    ERR_WEND_WITHOUT_WHILE = 30,
    ERR_FIELD_OVERFLOW = 50,
    ERR_INTERNAL_ERROR = 51,
    ERR_BAD_FILE_NUMBER = 52,
    ERR_FILE_NOT_FOUND = 53,
    ERR_BAD_FILE_MODE = 54,
    ERR_FILE_ALREADY_OPEN = 55,
    ERR_DEVICE_IO_ERROR = 57,
    ERR_FILE_ALREADY_EXISTS = 58,
    ERR_BAD_RECORD_LENGTH = 59,
    ERR_DISK_FULL = 61,
    ERR_INPUT_PAST_END = 62,
    ERR_BAD_RECORD_NUMBER = 63,
    ERR_BAD_FILE_NAME = 64,
    ERR_TOO_MANY_FILES = 67,
    ERR_PERMISSION_DENIED = 70,
    ERR_DISK_NOT_READY = 71,
    ERR_PATH_FILE_ACCESS_ERROR = 75,
    ERR_PATH_NOT_FOUND = 76
} RuntimeError;

#endif
